[package]
name = "hello_http"
version = "0.1.0"
authors = ["deb0ch <thomas.de.beauchene@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
